/**
 * Mock candidate fixtures for the SEARCH / DATA layer.
 *
 * These power `MockSearchProvider` so the whole Lightfern Reach demo runs with
 * zero API keys. Data is intentionally rich, specific and London/UK-flavored to
 * match the PRD demo ("pre-seed investors in London who back AI sales tools").
 *
 * Each candidate carries enough grounding facts in `fields` (2–4 each) for the
 * research layer to write credible notes, plus at least two plausible source
 * URLs (website / linkedin / press). IDs are stable (`mock-inv-01`, …) so runs
 * are reproducible. `source` is always `'mock'`.
 */
import type { Candidate, TargetType } from '../../types';

// ──────────────────────────────────────────────────────────────────────────
// Investors (people) — VC partners & angels in London backing AI / SaaS / GTM
// ──────────────────────────────────────────────────────────────────────────
const investors: Candidate[] = [
  {
    id: 'mock-inv-01',
    entity: 'people',
    name: 'Sarah Whitford',
    company: 'Foundersgate Capital',
    role: 'Partner',
    location: 'London, UK',
    url: 'https://foundersgate.vc',
    linkedin: 'https://www.linkedin.com/in/sarahwhitford',
    domain: 'foundersgate.vc',
    source: 'mock',
    fields: {
      thesis: 'Pre-seed and seed B2B SaaS with an AI-native wedge into go-to-market workflows.',
      stage: 'Pre-seed, Seed',
      check_size: '£150k–£600k',
      recent_post:
        'Posted "Why the next Outreach gets built on agents, not templates" on LinkedIn last week.',
      portfolio: ['Rivet (AI SDR)', 'Cadence Loop', 'Hellocast'],
      focus_areas: ['AI sales tools', 'GTM automation', 'vertical SaaS'],
    },
  },
  {
    id: 'mock-inv-02',
    entity: 'people',
    name: 'Daniel Osei',
    company: 'Northbank Ventures',
    role: 'General Partner',
    location: 'London, UK',
    url: 'https://northbank.ventures',
    linkedin: 'https://www.linkedin.com/in/danielosei',
    domain: 'northbank.ventures',
    source: 'mock',
    fields: {
      thesis: 'Backs technical founders building AI infrastructure and developer-first GTM tooling.',
      stage: 'Seed, Series A',
      check_size: '£500k–£2m',
      recent_post: 'Spoke at SaaStock London on "Agentic sales: the 2026 stack".',
      portfolio: ['Quayside AI', 'Teller', 'Brightpath Labs'],
      focus_areas: ['AI sales tools', 'dev tools', 'data infrastructure'],
    },
  },
  {
    id: 'mock-inv-03',
    entity: 'people',
    name: 'Priya Raman',
    company: 'Angel (ex-Revolut)',
    role: 'Angel Investor',
    location: 'London, UK',
    url: 'https://priyaraman.com',
    linkedin: 'https://www.linkedin.com/in/priyaraman',
    domain: 'priyaraman.com',
    source: 'mock',
    fields: {
      thesis: 'Operator-angel writing first cheques into AI-for-revenue and fintech-adjacent SaaS.',
      stage: 'Pre-seed',
      check_size: '£25k–£75k',
      recent_post: 'Shared "10 lessons scaling Revolut growth" thread (4k reposts).',
      portfolio: ['Sift Outbound', 'Ledgerly'],
      focus_areas: ['AI sales tools', 'fintech', 'growth'],
    },
  },
  {
    id: 'mock-inv-04',
    entity: 'people',
    name: 'Tom Bexley',
    company: 'Shoreditch Seed',
    role: 'Founding Partner',
    location: 'London, UK',
    url: 'https://shoreditchseed.com',
    linkedin: 'https://www.linkedin.com/in/tombexley',
    domain: 'shoreditchseed.com',
    source: 'mock',
    fields: {
      thesis: 'Pre-seed fund for AI applications with a clear ROI story for sales and marketing teams.',
      stage: 'Pre-seed',
      check_size: '£100k–£400k',
      recent_post: 'Published thesis memo "Selling to the sales team" on the fund blog.',
      portfolio: ['Outpace', 'Nudge AI', 'Coredeck'],
      focus_areas: ['AI sales tools', 'martech', 'PLG'],
    },
  },
  {
    id: 'mock-inv-05',
    entity: 'people',
    name: 'Eleanor Hayes',
    company: 'Thames Lane Partners',
    role: 'Principal',
    location: 'London, UK',
    url: 'https://thameslane.partners',
    linkedin: 'https://www.linkedin.com/in/eleanorhayes',
    domain: 'thameslane.partners',
    source: 'mock',
    fields: {
      thesis: 'Seed-stage applied AI across sales enablement, RevOps and customer intelligence.',
      stage: 'Seed',
      check_size: '£300k–£1.2m',
      recent_post: 'Hosted "RevOps + LLMs" founder dinner in Soho.',
      portfolio: ['Signalbox', 'Meriton AI'],
      focus_areas: ['AI sales tools', 'RevOps', 'customer data'],
    },
  },
  {
    id: 'mock-inv-06',
    entity: 'people',
    name: 'James Okonkwo',
    company: 'Camden Capital',
    role: 'Partner',
    location: 'London, UK',
    url: 'https://camdencapital.co.uk',
    linkedin: 'https://www.linkedin.com/in/jamesokonkwo',
    domain: 'camdencapital.co.uk',
    source: 'mock',
    fields: {
      thesis: 'Backs B2B AI that automates expensive human workflows; sales prospecting a core theme.',
      stage: 'Seed, Series A',
      check_size: '£500k–£2.5m',
      recent_post: 'Quoted in Sifted on the 2026 AI-SDR funding wave.',
      portfolio: ['Cabel', 'Resolv', 'Pitchwise'],
      focus_areas: ['AI sales tools', 'automation', 'B2B SaaS'],
    },
  },
  {
    id: 'mock-inv-07',
    entity: 'people',
    name: 'Hannah Fielding',
    company: 'Angel Syndicate (Seedling)',
    role: 'Angel Investor',
    location: 'London, UK',
    url: 'https://seedling.angel',
    linkedin: 'https://www.linkedin.com/in/hannahfielding',
    domain: 'seedling.angel',
    source: 'mock',
    fields: {
      thesis: 'Leads a 40-member angel syndicate into pre-seed AI sales and marketing tools.',
      stage: 'Pre-seed',
      check_size: '£50k–£250k (syndicated)',
      recent_post: 'Opened a syndicate allocation into an AI cold-email startup.',
      portfolio: ['Replyly', 'Foundry Outbound'],
      focus_areas: ['AI sales tools', 'outbound', 'angel syndicates'],
    },
  },
  {
    id: 'mock-inv-08',
    entity: 'people',
    name: 'Marcus Delaney',
    company: 'Old Street Ventures',
    role: 'Investment Partner',
    location: 'London, UK',
    url: 'https://oldstreet.vc',
    linkedin: 'https://www.linkedin.com/in/marcusdelaney',
    domain: 'oldstreet.vc',
    source: 'mock',
    fields: {
      thesis: 'Seed fund focused on AI copilots for revenue teams and the modern GTM stack.',
      stage: 'Seed',
      check_size: '£400k–£1.5m',
      recent_post: 'Wrote "The unbundling of the AE" on the fund Substack.',
      portfolio: ['Closer AI', 'Verda', 'Tandem GTM'],
      focus_areas: ['AI sales tools', 'sales copilots', 'GTM'],
      source_urls: [
        'https://oldstreet.vc/thesis',
        'https://www.sifted.eu/articles/ai-sdr-funding-2026',
      ],
    },
  },
  {
    id: 'mock-inv-09',
    entity: 'people',
    name: 'Amelia Croft',
    company: 'Kings Cross Angels',
    role: 'Lead Angel',
    location: 'London, UK',
    url: 'https://kingscrossangels.com',
    linkedin: 'https://www.linkedin.com/in/ameliacroft',
    domain: 'kingscrossangels.com',
    source: 'mock',
    fields: {
      thesis: 'Syndicate lead for pre-seed AI tools that replace manual GTM grunt work.',
      stage: 'Pre-seed',
      check_size: '£40k–£200k (syndicated)',
      recent_post: 'Hosted a Kings Cross founder breakfast on agentic outbound.',
      portfolio: ['Loopmail', 'QuotaPilot'],
      focus_areas: ['AI sales tools', 'outbound automation'],
      source_urls: [
        'https://kingscrossangels.com/portfolio',
        'https://techcrunch.com/tag/ai-sales',
      ],
    },
  },
  {
    id: 'mock-inv-10',
    entity: 'people',
    name: 'Robert Singh',
    company: 'Canary Wharf Capital',
    role: 'Managing Partner',
    location: 'London, UK',
    url: 'https://canarywharf.capital',
    linkedin: 'https://www.linkedin.com/in/robertsingh',
    domain: 'canarywharf.capital',
    source: 'mock',
    fields: {
      thesis: 'Seed fund backing UK founders selling AI workflow into enterprise revenue teams.',
      stage: 'Seed',
      check_size: '£750k–£3m',
      recent_post: 'Published Q1 2026 memo on "AI SDRs vs human AEs".',
      portfolio: ['Pipeline AI', 'Revforge', 'Stackline'],
      focus_areas: ['AI sales tools', 'enterprise SaaS', 'RevOps'],
      source_urls: [
        'https://canarywharf.capital/insights/ai-sdr-memo',
        'https://www.uktech.news/ai/seed-rounds-london-2026',
      ],
    },
  },
];

// ──────────────────────────────────────────────────────────────────────────
// Customers (people) — Heads of Operations at UK logistics / SaaS firms (50–500)
// ──────────────────────────────────────────────────────────────────────────
const customers: Candidate[] = [
  {
    id: 'mock-cus-01',
    entity: 'people',
    name: 'Rachel Thornton',
    company: 'Parcelhive Logistics',
    role: 'Head of Operations',
    location: 'Manchester, UK',
    url: 'https://parcelhive.co.uk',
    linkedin: 'https://www.linkedin.com/in/rachelthornton',
    domain: 'parcelhive.co.uk',
    source: 'mock',
    fields: {
      company_size: '120 employees',
      industry: 'Last-mile logistics',
      pain_point: 'Manual route planning and spreadsheet-driven dispatch across 6 depots.',
      recent_signal: 'Hiring an Operations Analyst and a RevOps lead per careers page.',
      tech_stack: ['Salesforce', 'Excel', 'Onfleet'],
    },
  },
  {
    id: 'mock-cus-02',
    entity: 'people',
    name: 'David Mensah',
    company: 'Cloudwell SaaS',
    role: 'Director of Operations',
    location: 'London, UK',
    url: 'https://cloudwell.io',
    linkedin: 'https://www.linkedin.com/in/davidmensah',
    domain: 'cloudwell.io',
    source: 'mock',
    fields: {
      company_size: '210 employees',
      industry: 'B2B SaaS (workflow software)',
      pain_point: 'Scaling onboarding ops without growing headcount linearly.',
      recent_signal: 'Closed a £9m Series B; expanding ops team.',
      tech_stack: ['HubSpot', 'Notion', 'Zapier'],
    },
  },
  {
    id: 'mock-cus-03',
    entity: 'people',
    name: 'Sophie Bellamy',
    company: 'Harbourfreight UK',
    role: 'Head of Operations',
    location: 'Bristol, UK',
    url: 'https://harbourfreight.co.uk',
    linkedin: 'https://www.linkedin.com/in/sophiebellamy',
    domain: 'harbourfreight.co.uk',
    source: 'mock',
    fields: {
      company_size: '340 employees',
      industry: 'Freight forwarding',
      pain_point: 'Customs paperwork and exception handling eat analyst time daily.',
      recent_signal: 'Rolled out a new TMS last quarter; still bridging gaps manually.',
      tech_stack: ['SAP', 'Power BI', 'Outlook'],
    },
  },
  {
    id: 'mock-cus-04',
    entity: 'people',
    name: 'Aaron Clarke',
    company: 'Stackmoor Software',
    role: 'VP Operations',
    location: 'Leeds, UK',
    url: 'https://stackmoor.com',
    linkedin: 'https://www.linkedin.com/in/aaronclarke',
    domain: 'stackmoor.com',
    source: 'mock',
    fields: {
      company_size: '160 employees',
      industry: 'B2B SaaS (HR tech)',
      pain_point: 'Disconnected tooling between sales, CS and finance ops.',
      recent_signal: 'Posted about evaluating revenue-operations platforms on LinkedIn.',
      tech_stack: ['Salesforce', 'Looker', 'Slack'],
    },
  },
  {
    id: 'mock-cus-05',
    entity: 'people',
    name: 'Nadia Hussain',
    company: 'Swiftcrate Fulfilment',
    role: 'Head of Operations',
    location: 'Birmingham, UK',
    url: 'https://swiftcrate.co.uk',
    linkedin: 'https://www.linkedin.com/in/nadiahussain',
    domain: 'swiftcrate.co.uk',
    source: 'mock',
    fields: {
      company_size: '270 employees',
      industry: '3PL / e-commerce fulfilment',
      pain_point: 'Peak-season staffing forecasts are guesswork; SLA breaches in Q4.',
      recent_signal: 'Opened a second warehouse near Birmingham this year.',
      tech_stack: ['NetSuite', 'ShipStation', 'Tableau'],
    },
  },
  {
    id: 'mock-cus-06',
    entity: 'people',
    name: 'Oliver Reyes',
    company: 'Meridian Cloud',
    role: 'Chief Operating Officer',
    location: 'London, UK',
    url: 'https://meridiancloud.io',
    linkedin: 'https://www.linkedin.com/in/oliverreyes',
    domain: 'meridiancloud.io',
    source: 'mock',
    fields: {
      company_size: '430 employees',
      industry: 'B2B SaaS (infrastructure)',
      pain_point: 'Operational reporting is stitched together across five tools.',
      recent_signal: 'Hired a new Head of RevOps; ops modernization underway.',
      tech_stack: ['Salesforce', 'dbt', 'Snowflake'],
    },
  },
  {
    id: 'mock-cus-07',
    entity: 'people',
    name: 'Charlotte Wren',
    company: 'Lochend Distribution',
    role: 'Operations Manager',
    location: 'Edinburgh, UK',
    url: 'https://lochend-dist.co.uk',
    linkedin: 'https://www.linkedin.com/in/charlottewren',
    domain: 'lochend-dist.co.uk',
    source: 'mock',
    fields: {
      company_size: '95 employees',
      industry: 'Regional distribution',
      pain_point: 'No single view of fleet utilisation; planning by phone and email.',
      recent_signal: 'Trialling telematics across the van fleet.',
      tech_stack: ['Microsoft Dynamics', 'Excel'],
    },
  },
  {
    id: 'mock-cus-08',
    entity: 'people',
    name: 'Benjamin Frost',
    company: 'Tideline Software',
    role: 'Head of Operations',
    location: 'London, UK',
    url: 'https://tideline.app',
    linkedin: 'https://www.linkedin.com/in/benjaminfrost',
    domain: 'tideline.app',
    source: 'mock',
    fields: {
      company_size: '180 employees',
      industry: 'B2B SaaS (fintech infrastructure)',
      pain_point: 'Manual reconciliation between billing and CRM slows month-end.',
      recent_signal: 'Job ad open for "Revenue Operations Manager".',
      tech_stack: ['HubSpot', 'Stripe', 'Google Sheets'],
      source_urls: [
        'https://tideline.app/careers',
        'https://www.linkedin.com/company/tideline-app',
      ],
    },
  },
  {
    id: 'mock-cus-09',
    entity: 'people',
    name: 'Imogen Walsh',
    company: 'Fleetline Couriers',
    role: 'Head of Operations',
    location: 'London, UK',
    url: 'https://fleetlinecouriers.co.uk',
    linkedin: 'https://www.linkedin.com/in/imogenwalsh',
    domain: 'fleetlinecouriers.co.uk',
    source: 'mock',
    fields: {
      company_size: '240 employees',
      industry: 'Same-day courier',
      pain_point: 'Dispatchers juggle three legacy systems during peak same-day volume.',
      recent_signal: 'Posted on LinkedIn about evaluating AI route-optimisation vendors.',
      tech_stack: ['Salesforce', 'Onfleet', 'Excel'],
      source_urls: [
        'https://fleetlinecouriers.co.uk/about',
        'https://www.linkedin.com/company/fleetline-couriers',
      ],
    },
  },
  {
    id: 'mock-cus-10',
    entity: 'people',
    name: 'Gregory Shaw',
    company: 'Northline Analytics',
    role: 'VP Operations',
    location: 'London, UK',
    url: 'https://northline.io',
    linkedin: 'https://www.linkedin.com/in/gregoryshaw',
    domain: 'northline.io',
    source: 'mock',
    fields: {
      company_size: '310 employees',
      industry: 'B2B SaaS (analytics)',
      pain_point: 'Customer onboarding ops bottlenecked on manual data checks.',
      recent_signal: 'Announced expansion of London HQ; hiring ops leads.',
      tech_stack: ['HubSpot', 'Snowflake', 'Looker'],
      source_urls: [
        'https://northline.io/blog/london-hq-expansion',
        'https://www.linkedin.com/company/northline-analytics',
      ],
    },
  },
];

// ──────────────────────────────────────────────────────────────────────────
// Startups (businesses) — seed-stage AI / compliance / GTM startups in London
// ──────────────────────────────────────────────────────────────────────────
const startups: Candidate[] = [
  {
    id: 'mock-str-01',
    entity: 'businesses',
    name: 'Rivet AI',
    company: 'Rivet AI',
    role: undefined,
    location: 'London, UK',
    url: 'https://rivet.ai',
    linkedin: 'https://www.linkedin.com/company/rivet-ai',
    domain: 'rivet.ai',
    source: 'mock',
    fields: {
      what_they_do: 'AI SDR that researches accounts and drafts personalised outbound at scale.',
      funding_stage: 'Seed',
      raised: '£3.1m seed (2025)',
      headcount: '22 employees',
      investors: ['Foundersgate Capital', 'angels from Revolut'],
    },
  },
  {
    id: 'mock-str-02',
    entity: 'businesses',
    name: 'Clauseware',
    company: 'Clauseware',
    role: undefined,
    location: 'London, UK',
    url: 'https://clauseware.com',
    linkedin: 'https://www.linkedin.com/company/clauseware',
    domain: 'clauseware.com',
    source: 'mock',
    fields: {
      what_they_do: 'AI contract-review and compliance copilot for in-house legal teams.',
      funding_stage: 'Seed',
      raised: '£2.4m seed (2025)',
      headcount: '17 employees',
      investors: ['Thames Lane Partners'],
    },
  },
  {
    id: 'mock-str-03',
    entity: 'businesses',
    name: 'Cadence Loop',
    company: 'Cadence Loop',
    role: undefined,
    location: 'London, UK',
    url: 'https://cadenceloop.io',
    linkedin: 'https://www.linkedin.com/company/cadence-loop',
    domain: 'cadenceloop.io',
    source: 'mock',
    fields: {
      what_they_do: 'GTM automation platform that orchestrates multichannel sales sequences with AI.',
      funding_stage: 'Pre-seed',
      raised: '£800k pre-seed (2026)',
      headcount: '9 employees',
      investors: ['Shoreditch Seed', 'Hannah Fielding (angel)'],
    },
  },
  {
    id: 'mock-str-04',
    entity: 'businesses',
    name: 'Signalbox',
    company: 'Signalbox',
    role: undefined,
    location: 'London, UK',
    url: 'https://signalbox.ai',
    linkedin: 'https://www.linkedin.com/company/signalbox-ai',
    domain: 'signalbox.ai',
    source: 'mock',
    fields: {
      what_they_do: 'Buyer-intent signals and account scoring for B2B revenue teams.',
      funding_stage: 'Seed',
      raised: '£4.0m seed (2025)',
      headcount: '28 employees',
      investors: ['Thames Lane Partners', 'Old Street Ventures'],
    },
  },
  {
    id: 'mock-str-05',
    entity: 'businesses',
    name: 'Verda Compliance',
    company: 'Verda Compliance',
    role: undefined,
    location: 'London, UK',
    url: 'https://verda.io',
    linkedin: 'https://www.linkedin.com/company/verda-compliance',
    domain: 'verda.io',
    source: 'mock',
    fields: {
      what_they_do: 'Automated SOC 2 and ISO 27001 evidence collection for fast-scaling startups.',
      funding_stage: 'Seed',
      raised: '£2.9m seed (2026)',
      headcount: '19 employees',
      investors: ['Old Street Ventures', 'Camden Capital'],
    },
  },
  {
    id: 'mock-str-06',
    entity: 'businesses',
    name: 'Closer AI',
    company: 'Closer AI',
    role: undefined,
    location: 'London, UK',
    url: 'https://closer.ai',
    linkedin: 'https://www.linkedin.com/company/closer-ai',
    domain: 'closer.ai',
    source: 'mock',
    fields: {
      what_they_do: 'Real-time AI sales copilot that coaches reps live on calls and drafts follow-ups.',
      funding_stage: 'Seed',
      raised: '£3.6m seed (2026)',
      headcount: '24 employees',
      investors: ['Old Street Ventures'],
    },
  },
  {
    id: 'mock-str-07',
    entity: 'businesses',
    name: 'Pitchwise',
    company: 'Pitchwise',
    role: undefined,
    location: 'London, UK',
    url: 'https://pitchwise.app',
    linkedin: 'https://www.linkedin.com/company/pitchwise',
    domain: 'pitchwise.app',
    source: 'mock',
    fields: {
      what_they_do: 'AI proposal and deck generator tuned for B2B sales motions.',
      funding_stage: 'Pre-seed',
      raised: '£600k pre-seed (2026)',
      headcount: '7 employees',
      investors: ['Camden Capital', 'angel syndicate'],
    },
  },
  {
    id: 'mock-str-08',
    entity: 'businesses',
    name: 'Tandem GTM',
    company: 'Tandem GTM',
    role: undefined,
    location: 'London, UK',
    url: 'https://tandemgtm.com',
    linkedin: 'https://www.linkedin.com/company/tandem-gtm',
    domain: 'tandemgtm.com',
    source: 'mock',
    fields: {
      what_they_do: 'Unified GTM data layer that syncs CRM, product usage and enrichment for RevOps.',
      funding_stage: 'Seed',
      raised: '£3.3m seed (2025)',
      headcount: '21 employees',
      investors: ['Old Street Ventures', 'Northbank Ventures'],
      source_urls: [
        'https://tandemgtm.com/blog/unified-gtm-data',
        'https://www.linkedin.com/company/tandem-gtm',
      ],
    },
  },
  {
    id: 'mock-str-09',
    entity: 'businesses',
    name: 'Ledgerly',
    company: 'Ledgerly',
    role: undefined,
    location: 'London, UK',
    url: 'https://ledgerly.io',
    linkedin: 'https://www.linkedin.com/company/ledgerly',
    domain: 'ledgerly.io',
    source: 'mock',
    fields: {
      what_they_do: 'AI revenue-recognition copilot for finance and RevOps teams at growth-stage SaaS.',
      funding_stage: 'Seed',
      raised: '£2.7m seed (2025)',
      headcount: '16 employees',
      investors: ['Priya Raman (angel)', 'Camden Capital'],
      source_urls: [
        'https://ledgerly.io/customers',
        'https://www.sifted.eu/articles/ledgerly-seed',
      ],
    },
  },
  {
    id: 'mock-str-10',
    entity: 'businesses',
    name: 'Outpace',
    company: 'Outpace',
    role: undefined,
    location: 'London, UK',
    url: 'https://outpace.ai',
    linkedin: 'https://www.linkedin.com/company/outpace-ai',
    domain: 'outpace.ai',
    source: 'mock',
    fields: {
      what_they_do: 'Multichannel AI outbound sequencer with built-in deliverability guardrails.',
      funding_stage: 'Pre-seed',
      raised: '£950k pre-seed (2026)',
      headcount: '11 employees',
      investors: ['Shoreditch Seed', 'Foundersgate Capital'],
      source_urls: [
        'https://outpace.ai/changelog',
        'https://techcrunch.com/tag/sales-automation',
      ],
    },
  },
];

// ──────────────────────────────────────────────────────────────────────────
// Local businesses (businesses) — independent shops in Shoreditch etc.;
// several flagged with "outdated website" signals for the demo.
// ──────────────────────────────────────────────────────────────────────────
const localBusinesses: Candidate[] = [
  {
    id: 'mock-loc-01',
    entity: 'businesses',
    name: 'Brick Lane Beans',
    company: 'Brick Lane Beans',
    role: undefined,
    location: 'Shoreditch, London, UK',
    url: 'http://bricklanebeans.co.uk',
    linkedin: undefined,
    domain: 'bricklanebeans.co.uk',
    source: 'mock',
    fields: {
      business_type: 'Independent coffee shop & roastery',
      headcount: '8 staff',
      website_signal: 'Outdated website — no online ordering, last updated 2019, not mobile-friendly.',
      footfall: 'Busy weekend market trade on Brick Lane.',
      socials: 'Active Instagram (12k followers) but no email capture.',
    },
  },
  {
    id: 'mock-loc-02',
    entity: 'businesses',
    name: 'Hoxton Hardware',
    company: 'Hoxton Hardware',
    role: undefined,
    location: 'Hoxton, London, UK',
    url: 'http://hoxtonhardware.co.uk',
    linkedin: undefined,
    domain: 'hoxtonhardware.co.uk',
    source: 'mock',
    fields: {
      business_type: 'Independent hardware & DIY shop',
      headcount: '5 staff',
      website_signal: 'Outdated website — static HTML, no stock listings, broken contact form.',
      footfall: 'Steady local trade from nearby flats and small builders.',
      socials: 'No social presence; relies on walk-ins.',
    },
  },
  {
    id: 'mock-loc-03',
    entity: 'businesses',
    name: 'The Curtain Road Deli',
    company: 'The Curtain Road Deli',
    role: undefined,
    location: 'Shoreditch, London, UK',
    url: 'https://curtainroaddeli.co.uk',
    linkedin: undefined,
    domain: 'curtainroaddeli.co.uk',
    source: 'mock',
    fields: {
      business_type: 'Independent deli & sandwich bar',
      headcount: '6 staff',
      website_signal: 'Modern one-pager but no online ordering or click-and-collect.',
      footfall: 'Weekday lunch rush from local studios and agencies.',
      socials: 'Instagram with daily specials.',
    },
  },
  {
    id: 'mock-loc-04',
    entity: 'businesses',
    name: 'Redchurch Bicycle Co.',
    company: 'Redchurch Bicycle Co.',
    role: undefined,
    location: 'Shoreditch, London, UK',
    url: 'http://redchurchbicycles.co.uk',
    linkedin: undefined,
    domain: 'redchurchbicycles.co.uk',
    source: 'mock',
    fields: {
      business_type: 'Independent bicycle shop & repair',
      headcount: '4 staff',
      website_signal: 'Outdated website — no booking system for repairs, photos from 2016.',
      footfall: 'Commuter repairs and weekend riders.',
      socials: 'Dormant Facebook page.',
    },
  },
  {
    id: 'mock-loc-05',
    entity: 'businesses',
    name: 'Columbia Road Florals',
    company: 'Columbia Road Florals',
    role: undefined,
    location: 'Bethnal Green, London, UK',
    url: 'http://columbiaroadflorals.co.uk',
    linkedin: undefined,
    domain: 'columbiaroadflorals.co.uk',
    source: 'mock',
    fields: {
      business_type: 'Independent florist',
      headcount: '3 staff',
      website_signal: 'Outdated website — no e-commerce, opening hours wrong, slow to load.',
      footfall: 'Heavy Sunday flower-market trade on Columbia Road.',
      socials: 'Strong Instagram following but all sales in person.',
    },
  },
  {
    id: 'mock-loc-06',
    entity: 'businesses',
    name: 'Old Spitalfields Bookshop',
    company: 'Old Spitalfields Bookshop',
    role: undefined,
    location: 'Spitalfields, London, UK',
    url: 'https://spitalfieldsbooks.co.uk',
    linkedin: undefined,
    domain: 'spitalfieldsbooks.co.uk',
    source: 'mock',
    fields: {
      business_type: 'Independent bookshop',
      headcount: '5 staff',
      website_signal: 'Has a Shopify store but rarely updated; stale event listings.',
      footfall: 'Tourists and locals from Spitalfields Market.',
      socials: 'Newsletter with ~2k subscribers.',
    },
  },
  {
    id: 'mock-loc-07',
    entity: 'businesses',
    name: 'Kingsland Barber Co.',
    company: 'Kingsland Barber Co.',
    role: undefined,
    location: 'Dalston, London, UK',
    url: 'http://kingslandbarber.co.uk',
    linkedin: undefined,
    domain: 'kingslandbarber.co.uk',
    source: 'mock',
    fields: {
      business_type: 'Independent barbershop',
      headcount: '6 staff',
      website_signal: 'Outdated website — phone-only bookings, no online calendar, broken gallery.',
      footfall: 'Loyal regulars; long Saturday queues.',
      socials: 'Instagram bookings via DM only.',
    },
  },
  {
    id: 'mock-loc-08',
    entity: 'businesses',
    name: 'Shoreditch Vinyl',
    company: 'Shoreditch Vinyl',
    role: undefined,
    location: 'Shoreditch, London, UK',
    url: 'http://shoreditchvinyl.co.uk',
    linkedin: undefined,
    domain: 'shoreditchvinyl.co.uk',
    source: 'mock',
    fields: {
      business_type: 'Independent record shop',
      headcount: '4 staff',
      website_signal: 'Outdated website — no online catalogue, Flash-era layout, no HTTPS.',
      footfall: 'Crate-diggers and tourists at weekends.',
      socials: 'Active on Instagram for new-stock drops.',
      source_urls: [
        'https://www.instagram.com/shoreditchvinyl',
        'https://www.timeout.com/london/shopping/shoreditch-vinyl',
      ],
    },
  },
  {
    id: 'mock-loc-09',
    entity: 'businesses',
    name: 'Spitalfields Tailors',
    company: 'Spitalfields Tailors',
    role: undefined,
    location: 'Spitalfields, London, UK',
    url: 'http://spitalfieldstailors.co.uk',
    linkedin: undefined,
    domain: 'spitalfieldstailors.co.uk',
    source: 'mock',
    fields: {
      business_type: 'Independent tailor & alterations',
      headcount: '4 staff',
      website_signal: 'Outdated website — no online booking, portfolio photos from 2018.',
      footfall: 'Office workers from Liverpool Street and market tourists.',
      socials: 'Google Business profile with strong reviews.',
      source_urls: [
        'https://g.page/spitalfields-tailors',
        'https://www.yell.com/biz/spitalfields-tailors-london',
      ],
    },
  },
  {
    id: 'mock-loc-10',
    entity: 'businesses',
    name: 'Hackney Pottery Studio',
    company: 'Hackney Pottery Studio',
    role: undefined,
    location: 'Hackney, London, UK',
    url: 'http://hackneypottery.co.uk',
    linkedin: undefined,
    domain: 'hackneypottery.co.uk',
    source: 'mock',
    fields: {
      business_type: 'Independent pottery workshop & classes',
      headcount: '3 staff',
      website_signal: 'Outdated website — class schedule PDF only, no checkout.',
      footfall: 'Weekend classes popular with local creatives.',
      socials: 'Instagram reels drive most enquiries.',
      source_urls: [
        'https://www.instagram.com/hackneypottery',
        'https://www.hackney.gov.uk/local-business-directory',
      ],
    },
  },
];

/**
 * Typed map of fixtures by target type. `MockSearchProvider` indexes this with
 * `brief.targetType` and the factory falls back to it whenever Unify fails.
 */
export const FIXTURES: Record<TargetType, Candidate[]> = {
  investors,
  customers,
  startups,
  local_businesses: localBusinesses,
};
